name: snapexpenses
description: snapexpenses- its about money 

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  intl: 
  timeago: ^2.0.26
  font_awesome_flutter: ^8.5.0
  flutter_money_formatter: ^0.8.3
  grouped_buttons: ^1.0.4
  camera: ^0.5.7+4

  image_picker: ^0.6.3+1
  modal_progress_hud: ^0.1.3
  auto_route: ^0.2.2
  
  moor: ^2.4.0
  moor_ffi: ^0.4.0
  path_provider: ^1.6.0
  path: ^1.6.4

  mobx: ^0.3.5
  flutter_mobx: ^0.3.0+1
  provider: ^4.0.4
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  auto_route_generator: ^0.2.2
  moor_generator: ^2.4.0
  mobx_codegen: ^0.3.3+1
  build_runner: ^1.7.4
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
